version: '3.8'

services:
  flaskapi:
    build: ./webapi
    enviroment:
      PRIVATE_KEY_BASE64: "ZGVpbmVpbnNpY2hlck1laXN0ZWdlbg=="  # ← Beispiel (Base64)
    container_name: flaskapi
    ports:
      - "5000:5000"
    volumes:
      - shared_data:/app/shared
    networks:
      - backend
      
  AdminPanel:
    build: ./adminpanel
    enviroment:
      ADMIN_LOGIN: "admin"  
      ADMIN_PASS: "ad-123456"  
    container_name: flaskapi
    ports:
      - "5080:5000"
    volumes:
      - shared_data:/app/shared
    networks:
      - backend
    enviroment:
      - FLASK_ENV=development

  samba:
    image: dperson/samba
    container_name: samba
    command: -u "smbuser;pass1234" -s "Expose;/mount/Expose;yes;no;no;smbuser"
    ports:
      - "445:445"
      - "139:139"
    volumes:
      - shared_data:/mount
    networks:
      - backend

volumes:
  shared_data:

networks:
  backend:
