version: '3.8'

services:
  flaskapi:
    build: ./webapi
    environment:  # ✅ richtig
      PRIVATE_KEY_BASE64: "ZGVpbmVpbnNpY2hlck1laXN0ZWdlbg=="
    container_name: flaskapi
    ports:
      - "5000:5000"
    volumes:
      - shared_data:/app/shared
    networks:
      - backend

  adminpanel:
    build: ./adminpanel
    environment:  # ✅ richtig
      ADMIN_LOGIN: "admin"
      ADMIN_PASS: "ad-123456"
    container_name: adminpanel  # 🔧 sollte nicht doppelt flaskapi heißen
    ports:
      - "5080:5000"
    volumes:
      - shared_data:/app/shared
    networks:
      - backend
    # command: sleep infinity

  samba:
    image: dperson/samba
    container_name: samba
    command: >
      sh -c "
      mkdir -p /mount/Expose/Listen /mount/Expose/Protokolle /mount/Expose/Archiv &&
      chown -R 100:101 /mount/Expose &&
      chmod -R 0775 /mount/Expose &&
      /usr/bin/samba.sh -u 'smbuser;pass1234' -s 'Expose;/mount/Expose;yes;no;yes;smbuser'
      "
    ports:
      - "445:445"
      - "139:139"
    volumes:
      - shared_data:/mount
    networks:
      - backend

volumes:
  shared_data:

networks:
  backend:
